apiVersion: v1

kind: Pod

metadata:
  name: webserver-pod

spec:

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: apache-container
    image: httpd
    volumeMounts:
    - name: shared-data
      mountPath: /var/www/html

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}