# kubectl create -f 1.nginx-service.yml
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-deploy-svc
  labels:
    app: nginx-web-label
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: nginx-web
