apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-web-label
    spec:
      containers:
      - name: nginx-web-container
        image: nginx:latest
        ports:
        - containerPort: 80
